-- Disable RLS on all tables
-- Security handled at API layer instead
ALTER TABLE "api_tokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "device_codes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "usage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_limits" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;
